# global: 

#   smtp_smarthost: 'smtp.gmail.com:587'
#   smtp_from: 'goldf55f@gmail.com'
#   smtp_auth_username: 'goldf55f@gmail.com'
#   smtp_auth_password: 'Abc@1234X'


inhibit_rules:
  - target_match:
      severity: "warning"
    source_match:
      severity: "critical"
    # Apply inhibition if the alertname and instance are the same.
    equal: ["alertname", "instance"]

route:
  receiver: "all"
  group_interval: 30s
  repeat_interval: 30s

  routes:
    - match:
        alertname: high_memory_load
      receiver: "telegram"
      repeat_interval: 1m
      continue: true

    - match:
        alertname: high_cpu_load
      receiver: "email"
      repeat_interval: 1m
      continue: true

    - match:
        alertname: high_cpu_load
      receiver: "sms"
      repeat_interval: 1m
      continue: true

    - match:
        alertname: high_storage_load
      receiver: "slack"
      repeat_interval: 1m
      continue: true


receivers:
  - name: "all"
    slack_configs:
      - send_resolved: true
        text: "{{ .CommonAnnotations.description }}"
        username: "Prometheus"
        channel: "#test"
        api_url: ""
    webhook_configs:
      - url: "https://telepush.dev/api/inlets/alertmanager/123d43"
        http_config:
    email_configs:
      - to: "manhduc030402@gmail.com"
        from: 'goldf55f@gmail.com'
        smarthost: 'smtp.gmail.com:587'
        auth_username: 'goldf55f@gmail.com'
        auth_password: 'cbpamuevasnbbnrb'
    # webhook_configs:
    #   - url: 'http://sms:9089/send'
    
    

  - name: "slack"
    slack_configs:
      - send_resolved: true
        text: "{{ .CommonAnnotations.description }}"
        username: "Prometheus"
        channel: "#test"
        api_url: ""

  - name: "telegram"
    webhook_configs:
      - url: "https://telepush.dev/api/inlets/alertmanager/123d43"
        http_config:


  - name: "email"
    email_configs:
      - to: "manhduc030402@gmail.com"
        from: 'goldf55f@gmail.com'
        smarthost: 'smtp.gmail.com:587'
        auth_username: 'goldf55f@gmail.com'
        auth_password: 'cbpamuevasnbbnrb'


  - name: "sms"
    webhook_configs:
      - url: 'http://0.0.0.0:9089/send'


